vich_uploader:
    db_driver: orm

    mappings:
       aliment_image:
           uri_prefix: /build/images
           upload_destination: '%kernel.project_dir%/assets/images'
       type_images:
            uri_prefix: /build/images
            upload_destination: '%kernel.project_dir%/assets/images'
